server:
  port: 8075


spring:
  application:
    name: buildorg

  datasource:
    driver: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://178.16.138.169:3308/
    username: root
    password: live@Bottomhalf_001